Importamos el csv que hemos subido al github personal de uno de los integrantes del equipo

In [11]:
import pandas as pd

money_dataframe = pd.read_csv("https://raw.githubusercontent.com/rubengr16/MachineLearning/main/Prac2/train.csv", sep=",")
money_dataframe

ID  Customer_ID  Month               Name   Age          SSN  \
0       43161         3985      4          Lawrencez  40.0  856431180.0   
1       40663        49494      2          Mohammedr  39.0  417453942.0   
2      111059         2925      6          Alistairn  17.0  499528888.0   
3       72139        21358      2       Dinesh Naire  22.0  859449371.0   
4      119841        21221      4             Bakerg  26.0  485239890.0   
...       ...          ...    ...                ...   ...          ...   
79995   42636        39869      7  Hendrik Sackmannb  50.0  217529489.0   
79996  114031        38305      2              Alexj  33.0   98861902.0   
79997   85991         9976      6     Luciana Lopezi  25.0  745835485.0   
79998   21240        13193      7      Edward Krudyd  15.0  894419091.0   
79999   73558        15294      5              Neilp  30.0   17531609.0   

          Occupation  Annual_Income  Monthly_Inhand_Salary  Num_Bank_Accounts  \
0         Accountant       97384.44            8167.370000                1.0   
1             Writer       31369.58            2607.131667                8.0   
2             Writer       30171.86            2772.321667                6.0   
3             Doctor       13100.02            1246.668333                7.0   
4             Doctor       62313.54            5120.795000                6.0   
...              ...            ...                    ...                ...   
79995  Media_Manager      107761.29            9047.107500                4.0   
79996      Scientist       16218.32            1098.526667                6.0   
79997       Engineer       29374.77            2377.897500                3.0   
79998        Manager       43782.45            3543.537500                6.0   
79999         Lawyer      102215.61            8482.967500                2.0   

       ...  Credit_Mix  Outstanding_Debt  Credit_Utilization_Ratio  \
0      ...        Good            405.45                 32.643281   
1      ...         Bad           4259.91                 39.375507   
2      ...         Bad           3406.51                 34.039021   
3      ...    Standard            727.29                 34.747262   
4      ...    Standard            817.64                 24.545394   
...    ...         ...               ...                       ...   
79995  ...    Standard             34.09                 41.899992   
79996  ...         Bad           4466.33                 24.275710   
79997  ...    Standard           1189.37                 38.439021   
79998  ...         Bad           3468.25                 24.233841   
79999  ...        Good             79.67                 27.903216   

      Credit_History_Age  Payment_of_Min_Amount  Total_EMI_per_month  \
0                  336.0                     No            77.284943   
1                  144.0                    Yes           171.748418   
2                  123.0                    Yes           205.403926   
3                  129.0                    Yes            41.177132   
4                  122.0                     NM           196.679642   
...                  ...                    ...                  ...   
79995              211.0                    Yes             0.000000   
79996               98.0                     NM            64.533114   
79997              241.0                     NM            40.264074   
79998               85.0                    Yes           240.664739   
79999              366.0                     No            60.567361   

       Amount_invested_monthly                 Payment_Behaviour  \
0                    53.714219   High_spent_Large_value_payments   
1                    44.990811   High_spent_Large_value_payments   
2                    40.781489   High_spent_Large_value_payments   
3                    23.005463    Low_spent_Large_value_payments   
4                    63.346750   Low_spent_Medium_value_payments   
...                    

In [12]:
import numpy as np
import sklearn.compose

def transformer_data(money_dataframe):
  # money_dataframe = regularizator(money_dataframe, ["Memory", "Speed"]) #  ??????
  np_money = np.array(money_dataframe)
  column_transformer = sklearn.compose.ColumnTransformer(transformers=[
      ("ID", "drop", [0]),
      ("Customer_ID", "drop", [1]),
      ("Month", "drop", [2]),
      ("Name", "drop", [3]),
      ("Age", sklearn.preprocessing.StandardScaler(), [4]),
      ("SSN", "drop", [5]),
      ("Occupation", "drop", [6]),
      ("Annual_Income", sklearn.preprocessing.StandardScaler(), [7]),
      ("Monthly_Inhand_Salary", sklearn.preprocessing.PowerTransformer(), [8]),
      ("Num_Bank_Accounts", sklearn.preprocessing.StandardScaler(), [9]),
      ("Num_Credit_Card", sklearn.preprocessing.StandardScaler(), [10]),
      ("Interest_Rate", sklearn.preprocessing.RobustScaler(), [11]),
      ("Num_of_Loan", sklearn.preprocessing.StandardScaler(), [12]),
      ("Type_of_Loan", "drop", [13]),
      ("Delay_from_due_date", sklearn.preprocessing.PowerTransformer(), [14]),
      ("Num_of_Delayed_Payment", sklearn.preprocessing.PowerTransformer(), [15]),
      ("Changed_Credit_Limit", sklearn.preprocessing.RobustScaler(), [16]),
      ("Num_Credit_Inquiries", sklearn.preprocessing.PowerTransformer(), [17]),
      ("Credit_Mix", sklearn.preprocessing.OrdinalEncoder(categories=[['Bad', 'Standard', 'Good']]), [18]),
      ("Outstanding_Debt", sklearn.preprocessing.PowerTransformer(), [19]),
      ("Credit_Utilization_Ratio", "drop", [20]),
      ("Credit_History_Age", sklearn.preprocessing.StandardScaler(), [21]),
      ("Payment_of_Min_Amount", sklearn.preprocessing.OrdinalEncoder(categories=[['Yes', 'No', 'NM']]), [22]),
      ("Total_EMI_per_month", "drop", [23]),
      ("Amount_invested_monthly", "drop", [24]),
      ("Payment_Behaviour", sklearn.preprocessing.OrdinalEncoder(categories=[['Low_spent_Large_value_payments', 'High_spent_Small_value_payments', 
                                                                              'High_spent_Medium_value_payments', 'Low_spent_Medium_value_payments', 
                                                                              'Low_spent_Small_value_payments', 'High_spent_Large_value_payments']]), [25]),
      ("Monthly_Balance", sklearn.preprocessing.PowerTransformer(), [26]),
      ("Credit_Score", sklearn.preprocessing.OrdinalEncoder(categories=[['Poor', 'Standard', 'Good']]), [27])
  ]);
  return column_transformer.fit_transform(np_money)

def transformer_test(money_dataframe):
  # money_dataframe = regularizator(money_dataframe, ["Memory", "Speed"]) #  ??????
  np_money = np.array(money_dataframe)
  column_transformer = sklearn.compose.ColumnTransformer(transformers=[
     ("ID", "drop", [0]),
      ("Customer_ID", "drop", [1]),
      ("Month", "drop", [2]),
      ("Name", "drop", [3]),
      ("Age", sklearn.preprocessing.StandardScaler(), [4]),
      ("SSN", "drop", [5]),
      ("Occupation", "drop", [6]),
      ("Annual_Income", sklearn.preprocessing.StandardScaler(), [7]),
      ("Monthly_Inhand_Salary", sklearn.preprocessing.PowerTransformer(), [8]),
      ("Num_Bank_Accounts", sklearn.preprocessing.StandardScaler(), [9]),
      ("Num_Credit_Card", sklearn.preprocessing.StandardScaler(), [10]),
      ("Interest_Rate", sklearn.preprocessing.RobustScaler(), [11]),
      ("Num_of_Loan", sklearn.preprocessing.StandardScaler(), [12]),
      ("Type_of_Loan", "drop", [13]),
      ("Delay_from_due_date", sklearn.preprocessing.PowerTransformer(), [14]),
      ("Num_of_Delayed_Payment", sklearn.preprocessing.PowerTransformer(), [15]),
      ("Changed_Credit_Limit", sklearn.preprocessing.RobustScaler(), [16]),
      ("Num_Credit_Inquiries", sklearn.preprocessing.PowerTransformer(), [17]),
      ("Credit_Mix", sklearn.preprocessing.OrdinalEncoder(categories=[['Bad', 'Standard', 'Good']]), [18]),
      ("Outstanding_Debt", sklearn.preprocessing.PowerTransformer(), [19]),
      ("Credit_Utilization_Ratio", "drop", [20]),
      ("Credit_History_Age", sklearn.preprocessing.StandardScaler(), [21]),
      ("Payment_of_Min_Amount", sklearn.preprocessing.OrdinalEncoder(categories=[['Yes', 'No', 'NM']]), [22]),
      ("Total_EMI_per_month", "drop", [23]),
      ("Amount_invested_monthly", "drop", [24]),
      ("Payment_Behaviour", sklearn.preprocessing.OrdinalEncoder(categories=[['Low_spent_Large_value_payments', 'High_spent_Small_value_payments', 
                                                                              'High_spent_Medium_value_payments', 'Low_spent_Medium_value_payments', 
                                                                              'Low_spent_Small_value_payments', 'High_spent_Large_value_payments']]), [25]),
      ("Monthly_Balance", sklearn.preprocessing.PowerTransformer(), [26])
  ]);
  return column_transformer.fit_transform(np_money)

Usamos iloc para separar el dataset entre data y target. Conociendo que tenemos 28 columnas, tomamos de la 0 a la 26 (incluidas, entonces 27 columnas) como data y la última restante como target

In [13]:
money_dataframe = transformer_data(money_dataframe)

X = money_dataframe[:, :26]
y = money_dataframe[:,-1:]

In [ ]:
y

array([[-0.30815404,  1.34470184,  1.27110421, -1.29400129, -0.25651339,
        -0.23076923, -1.03386662, -0.57054176, -0.69154243, -0.58061117,
         0.65186988,  2.        , -1.89062843,  1.45202176,  1.        ,
         3.        , -0.04131564,  2.        ]])

In [ ]:
money_dataframe

array([[ 0.62090227,  1.21887369,  1.21956977, ...,  5.        ,
         1.94550586,  1.        ],
       [ 0.52799663, -0.50048771, -0.25753698, ...,  5.        ,
        -0.48081896,  1.        ],
       [-1.51592724, -0.5316824 , -0.18165325, ...,  5.        ,
        -0.70315613,  1.        ],
       ...,
       [-0.77268219, -0.55244267, -0.37047955, ...,  2.        ,
         0.21418782,  1.        ],
       [-1.7017385 , -0.17719369,  0.12548986, ...,  0.        ,
        -1.51595964,  0.        ],
       [-0.30815404,  1.34470184,  1.27110421, ...,  3.        ,
        -0.04131564,  2.        ]])

In [ ]:
X

array([[ 0.62090227,  1.21887369,  1.21956977, -1.6788301 , -1.22350776,
        -0.38461538, -1.03386662,  0.15241112, -0.20995528, -0.93677555,
        -0.62796743,  2.        , -0.93807515,  1.15069181,  1.        ,
         5.        ,  1.94550586,  1.        ],
       [ 0.52799663, -0.50048771, -0.25753698,  1.01497154,  1.67747536,
         1.07692308,  1.82916594,  0.74857159,  1.87966171,  1.08429926,
         0.19457168,  0.        ,  1.86418067, -0.77781986,  0.        ,
         5.        , -0.48081896,  1.        ],
       [-1.51592724, -0.5316824 , -0.18165325,  0.24531393,  0.71048099,
         1.30769231,  2.23817059,  1.60407479,  0.75402708,  1.48366702,
         1.06372308,  0.        ,  1.48867159, -0.98875082,  0.        ,
         5.        , -0.70315613,  1.        ],
       [-1.05139909, -0.97631961, -1.13856779,  0.63014274, -0.25651339,
        -0.53846154,  0.60215199, -1.1420649 ,  1.07554289,  0.12961012,
         0.65186988,  1.        , -0.43985087, -0.928

Primero probamos con una validación justa para ir validando nuestro modelo y comprobar su eficiencia:

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=45)


In [ ]:
X_train

ID  Customer_ID  Month                Name   Age          SSN  \
10002   27139        48578      2        Alwyn Scottm  34.0  910305375.0   
2342    31825        32298      8     Maxwell Sonalie  39.0  425948273.0   
32388   10868         7486      3       Wayne Arnoldt  42.0  579151527.0   
62172   37986         2973      1                Kokm  21.0   30767737.0   
53570   29156        46563      3            Schererc  27.0  172010082.0   
...       ...          ...    ...                 ...   ...          ...   
12895  126969        13643      4               Moong  25.0  864921050.0   
60960  146310         5456      1           Scuffhamm  37.0  290341014.0   
6012    58896        28359      7             Wilkess  41.0  166557075.0   
63107   88125        12601      4           Scheyderk  18.0  490805398.0   
6558    61602        11602      1  Tetsushi Kajimotov  18.0  566075369.0   

          Occupation  Annual_Income  Monthly_Inhand_Salary  Num_Bank_Accounts  \
10002      Developer      172891.36           14156.613333                3.0   
2342          Writer       18122.37            1794.197500                3.0   
32388      Architect       41499.21            3582.267500                0.0   
62172       Mechanic       51506.55            4051.212500                4.0   
53570       Musician       32763.68            2616.306667                7.0   
...              ...            ...                    ...                ...   
12895  Media_Manager       55263.82            4881.318333                4.0   
60960       Musician       48996.08            3799.006667                5.0   
6012       Scientist      114150.75            9668.562500                5.0   
63107     Accountant       19369.96            1791.163333                6.0   
6558      Journalist      126971.00           10672.916667                0.0   

       ...  Changed_Credit_Limit  Num_Credit_Inquiries  Credit_Mix  \
10002  ...                  5.93                   3.0        Good   
2342   ...                 15.33                   7.0    Standard   
32388  ...                  9.79                   4.0        Good   
62172  ...                 11.40                   4.0    Standard   
53570  ...                 16.30                   8.0    Standard   
...    ...                   ...                   ...         ...   
12895  ...                 13.76                   6.0    Standard   
60960  ...                 13.31                   1.0    Standard   
6012   ...                  9.13                   0.0        Good   
63107  ...                 24.39                   8.0    Standard   
6558   ...                 11.83                   1.0        Good   

      Outstanding_Debt  Credit_Utilization_Ratio  Credit_History_Age  \
10002           922.15                 34.574870               323.0   
2342           2686.50                 22.831465               194.0   
32388          1272.15                 39.636020               185.0   
62172          2681.39                 39.036190                99.0   
53570           574.82                 34.272520               221.0   
...                ...                       ...                 ...   
12895          1051.33                 33.281165               289.0   
60960           285.29                 28.944479               213.0   
6012            399.84                 35.873278               230.0   
63107          1266.31                 29.836572               191.0   
6558            772.58                 35.807621               213.0   

       Payment_of_Min_Amount  Total_EMI_per_month Amount_invested_monthly  \
10002                     No           272.812226              166.390095   
2342                     Yes            76.142588               47.697342   
32388                     No             0.000000               75.000587   
62172                    Yes           160.992411               58.063275   
53570                    Yes      

In [14]:
from sklearn.ensemble import RandomForestClassifier

rfc = RandomForestClassifier(n_estimators=100)

rfc.fit(X,y)
# rfc.fit(X_train,y_train)

# y_pred = rfc.predict(X_test)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  """


RandomForestClassifier()

In [ ]:
y_pred

array([2., 1., 1., ..., 0., 1., 0.])

In [6]:
from sklearn.ensemble import RandomForestClassifier

rfc = RandomForestClassifier(n_estimators=100)

rfc.fit(X, y)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  """


RandomForestClassifier()

In [15]:
test_dataframe = pd.read_csv("https://raw.githubusercontent.com/rubengr16/MachineLearning/main/Prac2/test.csv", sep=",")

test_dataframe = transformer_test(test_dataframe)


y_pred = rfc.predict(test_dataframe)

ValueError: ignored

In [ ]:
prediction_dataframe = pd.DataFrame(y_pred)

ids = test_dataframe.iloc[:,0]
credit_score_dict = {0: 'Poor', 1: 'Standard', 2: 'Good'}
for i in range(len(y_pred)):
  submit = pd.concat([ids,credit_score_dict[y_pred[i]]], axis=1)
submit.columns=['ID','Credit_Score']

#for i in range(len(submit)):
 # submit.loc[i, 'Credit_Score'] = cambio_credit(submit.loc[i, 'Credit_Score'])

submit.to_csv("Prac2.csv", index=False)